### ISSUE TITLE
Spine animation support?

### ISSUE THREAD

**Issue by subsoap** [britzl/defold-richtext#13]
Like texture it would be useful for animated emoticons with lower space requirements

**Comment by britzl** [comment]
I realised when testing that spine animations are a bit tricker. They always have a size of 1x1 and ignore pivot. This is to some extent understandable since the bounding box of a spine animation will change over time while animating.

But it also makes it hard to position spine models together with text in a gui. Animated emoticons like you suggested should probably use normal flipbook animations instead.

**Comment by britzl** [comment]
Added support for spine models. Spine models will be aligned to bottom of line. You need to manually add space characters around the model since size isn't reported.

https://github.com/britzl/defold-richtext/releases/tag/2.7.0
